highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


url: http://ericloy.github.io/
baseurl: /LoyLit/
title: Eric C. Loy
author: Eric C. Loy
description: Academic portfolio and contact information for Eric C. Loy.
avatar: profile2.png
email: eric.christian.loy@email.com
github: ericloy # username
twitter: eric_loy
# linkedin: username
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
